import { IAPTEngagementData } from "../interfaces/IAPTEngagement";

export const dummyDashboardData: IAPTEngagementData[] = [
  {
    engagementId: "67723722-08ac-47b9-a0a1-dd471e1cd5de",
    projectId: "d7f4c4c6-9e6f-4d3d-9b0e-2b7c4c1b4d2d",
    clientId: "c3b0f3a6-8a2a-4b0b-8a3e-9b3a4c2b1a2a",
    engagementState: 0,
    engagementName: "Engagement 1",
    clientName: "Client 1",
    engagementBase: "Engagement Base 1",
    engagementGroup: "Engagement Group 1",
    entityName: "Entity Name 1",
    entityNameStateDate: "25/01/2024",
    entityType: "Entity Type 1",
    groupEngagement: "Group Engagement 1",
    language: "Language 1",
    engagementType: "Engagement Type 1",
    startDate: "01/01/2024",
    endDate: "01/02/2024",
    preparer: "Preparer 1",
    reviewer: "Reviewer 1",
    validator: "Validator 1",
  },
  {
    engagementId: "67723722-08ac-47b9-a0a1-dd471e1cd5de",
    projectId: "d7f4c4c6-9e6f-4d3d-9b0e-2b7c4c1b4d2d",
    clientId: "c3b0f3a6-8a2a-4b0b-8a3e-9b3a4c2b1a2a",
    engagementState: 1,
    engagementName: "Engagement 2",
    clientName: "Client 2",
    engagementBase: "Engagement Base 2",
    engagementGroup: "Engagement Group 2",
    entityName: "Entity Name 2",
    entityNameStateDate: "25/01/2024",
    entityType: "Entity Type 2",
    groupEngagement: "Group Engagement 2",
    language: "Language 2",
    engagementType: "Engagement Type 2",
    startDate: "01/01/2024",
    endDate: "01/02/2024",
    preparer: "Preparer 2",
    reviewer: "Reviewer 2",
  },
  {
    engagementId: "67723722-08ac-47b9-a0a1-dd471e1cd5de",
    projectId: "d7f4c4c6-9e6f-4d3d-9b0e-2b7c4c1b4d2d",
    clientId: "c3b0f3a6-8a2a-4b0b-8a3e-9b3a4c2b1a2a",
    engagementState: 2,
    engagementName: "Engagement 3",
    clientName: "Client 3",
    engagementBase: "Engagement Base 3",
    engagementGroup: "Engagement Group 3",
    entityName: "Entity Name 3",
    entityNameStateDate: "25/01/2024",
    entityType: "Entity Type 3",
    groupEngagement: "Group Engagement 3",
    language: "Language 3",
    engagementType: "Engagement Type 3",
    startDate: "01/01/2024",
    endDate: "01/02/2024",
    preparer: "Preparer 3",
    reviewer: "Reviewer 3",
  },
  {
    engagementId: "67723722-08ac-47b9-a0a1-dd471e1cd5de",
    projectId: "d7f4c4c6-9e6f-4d3d-9b0e-2b7c4c1b4d2d",
    clientId: "c3b0f3a6-8a2a-4b0b-8a3e-9b3a4c2b1a2a",
    engagementState: 3,
    engagementName: "Engagement 4",
    clientName: "Client 4",
    engagementBase: "Engagement Base 4",
    engagementGroup: "Engagement Group 4",
    entityName: "Entity Name 4",
    entityNameStateDate: "25/01/2024",
    entityType: "Entity Type 4",
    groupEngagement: "Group Engagement 4",
    language: "Language 4",
    engagementType: "Engagement Type 4",
    startDate: "01/01/2024",
    endDate: "01/02/2024",
    preparer: "Preparer 4",
    reviewer: "Reviewer 4",
  },
];

export const dummyAssignTrialBalanceData = {
  numberOfTabs: 3,
  singleTab: false,
  tabDetails: [
    {
      tabIndex: 1,
      tabName: "Polar Seafish Limited",
    },
    {
      tabIndex: 2,
      tabName: "Initial TB",
    },
    {
      tabIndex: 3,
      tabName: "Formatted TB",
    },
  ],
  headerDetails: [
    {
      headerColumnIndex: 1,
      headerColumnName: "AccountCode",
    },
    {
      headerColumnIndex: 2,
      headerColumnName: "AccountName",
    },
    {
      headerColumnIndex: 3,
      headerColumnName: "FY22Balance",
    },
    {
      headerColumnIndex: 4,
      headerColumnName: "IncomeStatementBalanceSheet",
    },
  ],
  accountDataTabIndex: 1,
  accountDataTabName: "Polar Seafish Limited",
  accountDataTabRows: 156,
  accountDataTabHeaders: {
    AccountNumberColumnLetter: "A",
    AccountNameColumnLetter: "B",
    FinancialStatementTypeColumnLetter: "D",
    AmountColumnLetter: "C",
  },
  headerRow: 2,
  staringRow: 3,
  endingRow: 156,
  excelData: [
    {
      rows: '[\r\n  {\r\n    "AccountCode": "11101",\r\n    "AccountName": "Cost - Vessel",\r\n    "FY22Balance": "27207557",\r\n    "IncomeStatementBalanceSheet": "Balance Sheet"\r\n  },\r\n  {\r\n    "AccountCode": "11102",\r\n    "AccountName": "Deprecation - Vessel",\r\n    "FY22Balance": "-2388595",\r\n    "IncomeStatementBalanceSheet": "Balance Sheet"\r\n  },\r\n  {\r\n    "AccountCode": "11161",\r\n    "AccountName": "Cost -     Motor Vehicles",\r\n    "FY22Balance": "380069",\r\n    "IncomeStatementBalanceSheet": "Balance Sheet"\r\n  },\r\n  {\r\n    "AccountCode": "11162",\r\n    "AccountName": "Deprecation -     Motor Vehicles",\r\n    "FY22Balance": "-57355",\r\n    "IncomeStatementBalanceSheet": "Balance Sheet"\r\n  },\r\n  {\r\n    "AccountCode": "11171",\r\n    "AccountName": "Cost - Land and Buildings",\r\n    "FY22Balance": "4167055",\r\n    "IncomeStatementBalanceSheet": "Balance Sheet"\r\n  },\r\n  {\r\n    "AccountCode": "11172",\r\n    "AccountName": "Deprecation - Land and Buildings",\r\n    "FY22Balance": "-170558",\r\n    "IncomeStatementBalanceSheet": "Balance Sheet"\r\n  },\r\n  {\r\n    "AccountCode": "11181",\r\n    "AccountName": "Cost - Plant and machinery",\r\n    "FY22Balance": "212201",\r\n    "IncomeStatementBalanceSheet": "Balance Sheet"\r\n  },\r\n  {\r\n    "AccountCode": "11182",\r\n    "AccountName": "Depreciation - Plant and machinery",\r\n    "FY22Balance": "-34859",\r\n    "IncomeStatementBalanceSheet": "Balance Sheet"\r\n  },\r\n  {\r\n    "AccountCode": "11191",\r\n    "AccountName": "Cost - Fixtures and fittings",\r\n    "FY22Balance": "102898",\r\n    "IncomeStatementBalanceSheet": "Balance Sheet"\r\n  },\r\n  {\r\n    "AccountCode": "11192",\r\n    "AccountName": "Deprecation  - Fixtures and fittings",\r\n    "FY22Balance": "-16104",\r\n    "IncomeStatementBalanceSheet": "Balance Sheet"\r\n  }\r\n]',
    },
    {
      rows: '[\r\n  {\r\n    "AccountCode": "73020",\r\n    "AccountName": "Income from Vessel Agreements",\r\n    "FY22Balance": "0",\r\n    "IncomeStatementBalanceSheet": "Income Statement"\r\n  },\r\n  {\r\n    "AccountCode": "73040",\r\n    "AccountName": "Interest from FI Banks",\r\n    "FY22Balance": "-274",\r\n    "IncomeStatementBalanceSheet": "Income Statement"\r\n  },\r\n  {\r\n    "AccountCode": "73060",\r\n    "AccountName": "Interest receivable Bank/Loan",\r\n    "FY22Balance": "-300467",\r\n    "IncomeStatementBalanceSheet": "Income Statement"\r\n  },\r\n  {\r\n    "AccountCode": "73080",\r\n    "AccountName": "Dividends received",\r\n    "FY22Balance": "0",\r\n    "IncomeStatementBalanceSheet": "Income Statement"\r\n  },\r\n  {\r\n    "AccountCode": "73100",\r\n    "AccountName": "Extraordinary Income",\r\n    "FY22Balance": "-468714",\r\n    "IncomeStatementBalanceSheet": "Income Statement"\r\n  },\r\n  {\r\n    "AccountCode": "80100",\r\n    "AccountName": "Vessels",\r\n    "FY22Balance": "2388595",\r\n    "IncomeStatementBalanceSheet": "Income Statement"\r\n  },\r\n  {\r\n    "AccountCode": "80300",\r\n    "AccountName": "Motor Vehciles",\r\n    "FY22Balance": "57355",\r\n    "IncomeStatementBalanceSheet": "Income Statement"\r\n  },\r\n  {\r\n    "AccountCode": "80350",\r\n    "AccountName": "P&M",\r\n    "FY22Balance": "34859",\r\n    "IncomeStatementBalanceSheet": "Income Statement"\r\n  },\r\n  {\r\n    "AccountCode": "80400",\r\n    "AccountName": "Office Equip",\r\n    "FY22Balance": "16104",\r\n    "IncomeStatementBalanceSheet": "Income Statement"\r\n  },\r\n  {\r\n    "AccountCode": "80450",\r\n    "AccountName": "Property",\r\n    "FY22Balance": "170558",\r\n    "IncomeStatementBalanceSheet": "Income Statement"\r\n  }\r\n]',
    },
  ],
};
